### PR TITLE
Weather file operations and more

### PR DESCRIPTION
**Pull request by Myoldmopar**
A collection of fixes, but the big stuff will be a quick overhaul of the weather file operation.

Fixes:
 - #63 (close dialogs when closing the app)
 - #97 (add setting to keep workflow dialogs open)
 - #96 (adds program icon)
 - #89 and #95 (polished up weather file support in general)

Additional Stuff from Chat:
 - ~~Enable weather button only after file selected~~
   - I don't think I'll do this right now, the dialog helps the user know what to do
 - [x] Change DDONly to something else "No Weather File"
 - [x] Use Radio Buttons on Weather dialog (could use refinement, but it's in place at least)
 - [x] Get rid of the context from the dropdown
 - [x] Invalidate the whole UI once GUI is built (hopefully this works--haven't tested)
 - [x] Link to help, quickstart, docs, etc. from app help menu
 - [x] One time dialog with link to RTD
 - [x] Update workflows after dialog finds new workflows
 - [x] Paths need quotes - shell, external program, some sort of audit
 - [x] Version column from E+ workflow, is it IDF?  It's the IDF version, I modified a file and it showed up
 - [x] Background process to get version info for files (Issue opened - NOT Fixed)

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@JasonGlazer OK, this is a big change.  I think I'm close to implementing exactly what we talked about the other day.  Would you be able to chat tomorrow morning so I can show you how it works and we can resolve any other issues prior to release?

**Comment by JasonGlazer** [comment]
Great, I would love to see it 10am tomorrow?

**Comment by Myoldmopar** [comment]
Should be OK, I may have to step away from our chat for a separate 5 minute chat at 1015, but I think that's still a good time to do it.

**Comment by JasonGlazer** [comment]
Is 9 or 11 better?

**Comment by Myoldmopar** [comment]
9 is better if that works.

**Comment by JasonGlazer** [comment]
Sure

**Comment by JasonGlazer** [comment]
I will take a look

**Comment by Myoldmopar** [comment]
Sounds good.  I'm having a bit of trouble working with CI here.  The app keeps trying to show the welcome dialog the first time it's opened, and on CI, that means the dialog just stays open forever.  I'm trying to **not** show it on CI, but it's not that easy.

**Comment by JasonGlazer** [comment]
@Myoldmopar I noticed the weather column on the main grid is very narrow when first opened. The revised weather selection dialog looks great. If it is not too difficult, you might want to select the radio button when an action takes place such as when find on disk is pressed the radio button should go to "selected EPW"

**Comment by Myoldmopar** [comment]
Hmmmm so the interface also doesn't know about whether a workflow is E+ related or not, so it doesn't know whether the user **actually** needs to select a weather file.  For transition, as an example, the weather file doesn't need to be specified, but the user will have to pick one.  This isn't good.

The **best** possible option, is to add one more optional function to the workflow class, that doesn't have to be overridden, that tells the interface if the workflow wants a weather file.  This way the interface won't show the column for unrelated workflows, it won't ask the user for it if it's not related, and then if it is a weather-file-based workflow, it will all work nicely.

Again, this function will be optional.  It won't break any of the existing workflows.  It will by default return False so that new workflows don't need a weather file.  However, for our E+ workflows, we will override it and return True.

**Comment by Myoldmopar** [comment]
OK, I think everything has been addressed.  The columns are now sized nicely.  The weather dialog now selects radio buttons when an action is done.  I then made a big refinement for the interface through adding a workflow function called "uses_weather".  Most workflows won't know about this function, and the base class function will just return False.  In this case, the interface won't do any weather data stuff.  Nice.  But then EnergyPlus workflows will return True, in which case the weather data column will be shown, and the weather data interface will be required before running the workflow.  I think this is a great, important addition.

**Comment by JasonGlazer** [comment]
Sounds like a good solution. Maybe "uses_weather" should be true for the CalcSoilSurfTemp workflow also.

**Comment by Myoldmopar** [comment]
Thanks @JasonGlazer, it can't really be true for CalcSoilSurfTemp.  For that workflow, the workflow is actually operating **on** the epw, not using it as a support file.  If you turned it on for CalcSoilSurfTemp, you would browse to an epw file in the file control, run the workflow, and have to also select an epw file there.  

I am making a couple super minor improvements to the workflows now over in E+ land, just adding useful output messages to the output dialog so far.  As far as I can tell this massive branch is now ready to drop in.

**Comment by JasonGlazer** [comment]
Yes, you are right. No need to select the weather file twice for CalcSoilSurfTemp.

**Pull request merged**
