### PR TITLE
Restore settings version options

### PR DESCRIPTION
**Pull request by JasonGlazer**
Address #17

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar when EP-Launch just starts the workflow list is getting overpopulated with all the version options.

image

Then if I use Settings..Version..8.9.0 I get 

image

Note that no workflow from the list is selected anymore. 

I started to add some code frame.py 100:105 but it seems like you rearranged some of this code and maybe you should let me know what you intent was.

Also does it work this way on MacOS or Linux?

**Comment by JasonGlazer** [comment]
This should address #37, #38, #34, #17

**Comment by Myoldmopar** [comment]
> This should address #37, #38, #34, #17

That's fantastic!

**Comment by JasonGlazer** [comment]
@Myoldmopar do you want to review this or should I just merge it?

**Comment by Myoldmopar** [comment]
You can merge.  I will still verify it is functioning, but I don't want to leave the branch for too long.

**Pull request merged**
