### PR TITLE
Much improved callback support

### PR DESCRIPTION
**Pull request by Myoldmopar**
I got some caffeine, and decided to flesh out the callbacks.  For one thing, the E+ binary I was calling earlier today was fracked somehow and it was messing up stdout, so I spent hours trying Python fixes when it was technically unfixable.  Gross.

Anyway, now the output comes line-by-line...if you run a long running input file (think `RefBldgHospitalNew2004_Chicago`) you should be able to watch the output go by nice and steady.

And the mechanics for this are so dang smooth now.  There is a static method on the workflow base class called `execute_for_callback`.  It is a generator function that can yield values each time it's called.  In this case it's returning output lines from the command being run.  When combined with the pre-wired `callback` function I added earlier today to the workflow base class, the process for a workflow to provide  output to the GUI has reduced to this:

```python
try:
    for message in BaseEPLaunch3Workflow.execute_for_callback(['ping', '-c', '5', 'google.com'], '/home'):
        self.callback(message)
    return EPLaunch3WorkflowResponse(True, 'Ping Complete', {})
except subprocess.CalledProcessError:
    return EPLaunch3WorkflowResponse(False, 'Not sure why but it failed', {})
```

In a real-world workflow, you'd probably provide more diagnostic data during a run:

```python
self.callback("Hey I'm going to run a PING now")
try:
    for message in BaseEPLaunch3Workflow.execute_for_callback(['ping', '-c', '5', 'google.com'], '/home'):
        self.callback(message)
    self.callback("Hey PING is done now")
    # parse some output into a variable called responsetime
    return EPLaunch3WorkflowResponse(True, 'Ping Complete', {'time': responsetime})
except subprocess.CalledProcessError:
    self.callback("PING Failed")
    return EPLaunch3WorkflowResponse(False, 'Not sure why but it failed', {})
```

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I mean look at this.  Full disclosure, I'm going to sleep so much better tonight knowing I have this functioning this well.

Goodnight @JasonGlazer 

eplaunch

**Comment by JasonGlazer** [comment]
@Myoldmopar Good morning. That worked for me. 

Although I did have to move the workflow files to where I have EnergyPlus installed. The "builtin" location did not seem to work.

**Comment by JasonGlazer** [comment]
Feel free to merge this when you are ready.

**Comment by JasonGlazer** [comment]
Any chance of simplifying the code that appears in the workflows python files? Since they are most likely to be user modified, it would be nice if starting an application was a simple call.

**Comment by JasonGlazer** [comment]
Nice adding the dialog although I ended up with them littered around by desktop. Maybe the dialog should automatically close unless their is an error? Or maybe have an option that does that?

**Comment by Myoldmopar** [comment]
[workflow_output_2.zip](https://github.com/NREL/EP-Launch/files/2276436/workflow_output_2.zip)

I'm not sure what you mean when you say they were littered around the desktop.  This mpeg shows what I see and what I was going for when I laid out the dialog placement logic.  It's really quite smooth...

I had intended on not working on this any more this week, but at this point I think I'm planning on working on this tomorrow, polishing up all this stuff, trying to squash as many bugs as possible, and then walking away for a couple weeks.  It's really **really** coming along now.  I am excited to get this out there.

**Comment by JasonGlazer** [comment]
Sorry, "littered around" was an overstatement. They do come out in a column next to the window but they pile up on each other and don't go away unless the user takes an action. After about 10 simulation, they just seem like unnecessary stuff sitting around. I guess I'm not a fan of the GUI for these. A user now needs to clean up after themselves. Generally, not an impression that you want to give to a user. I guess it is ok for the beta but it could be made much better. 

Perhaps instead, a single window. with a list. On the list is the file names, workflow name, and timestamp of when the run started. When you click on an item on the list, it shows the progress. Maybe the list shows both currently running a simulations run earlier that day also with a status indicating if they are complete or not.

**Comment by Myoldmopar** [comment]
That's all fair.  I guess I was thinking more pessimistic where there would likely be a problem and the user would want to be able to see the output.  As I developed the workflow stuff, I constantly saw little issues so I wanted to clearly watch the output.  For most users the simulations will run successfully.  So they will want them to show up and then disappear.

It would be a bit of a lift to try to make the list and keep all the output tracked within the main GUI.  From the amount of time I have left, I think there are two options:
 - Always close the window when it is done
 - Close the window if a simulation succeeds, leave it open if it failed

In a later version, we could add a switch so the user can decide between:
 - Always stay open
 - Stay open on failure
 - Always closed

And in an even later version we can have a list of all the simulations run and be able to pull up the output on demand.

**Comment by JasonGlazer** [comment]
I think the "Close the window if a simulation succeeds, leave it open if it failed" option makes sense for now.

**Comment by Myoldmopar** [comment]
:+1: :+1:

**Pull request merged**
