### PR TITLE
Update the file grid weather column cell when a weather favorite/recent is selected

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses #113

### CODE REVIEW

**Comment by JasonGlazer** [comment]
Small fix. Just copied some code from the "select" weather menu to update the main grid.

**Comment by Myoldmopar** [comment]
@JasonGlazer I don't really understand, this PR was closed but not merged.  Was that intentional?

**Comment by JasonGlazer** [comment]
Sorry, pressed the wrong button.

**Comment by Myoldmopar** [comment]
OK, cool.  I'll make RC3 right now.  If we feel good about everything then that can be v3.0.

**Pull request merged**
