### PR TITLE
Fix multiple selected weather files

### PR DESCRIPTION
**Pull request by JasonGlazer**
Fixes to #36

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar I'm getting a flake8 issue with some code that is in master. Weirdly it doesn't show up when I run flake8 locally.

**Comment by JasonGlazer** [comment]
@Myoldmopar flake8 is complaining no matter how those line breaks are. Any ideas?

**Comment by Myoldmopar** [comment]
OK, I think I fixed your particular flake8 issues, but I may have introduced a different couple.  If this is still red once 6ad083e is done I'll push another fix to it.

**Comment by JasonGlazer** [comment]
Flake8 just doesn't like anything :-)

**Comment by Myoldmopar** [comment]
We have flake8 defined as a dependency in the Tox configuration file.  We don't have it locked to a specific version of flake8.  Because of this, I think maybe flake8 went through an update and became more scrutinizing.  Anyway, breaking lines with operators in Python is one specific area that I can't remember off the top of my head how to do it right.  Making the variable names super short and putting it all in one line seems to work here though :smile: 

OK, so I accidentally hijacked this branch to test out the transition changes.  If you have a chance, could you pull this branch back down and test converting an 8.9 file to 9.0 using both 9.0.0 and 9.0.1?  It **should** work on Windows for both now.  It will work on Linux once the `transition.py` file gets fixed over in E+ land.

**Comment by Myoldmopar** [comment]
@JasonGlazer 
Just tested this on Windows.  Even with the transition.py as it was with the E+ 9.0.0 and 9.0.1 releases, the transitions from 8.9.0 to **either** 9.0.0 or 9.0.1 work perfectly.  This is good.  I'm going to merge this, close the issues, and tag a release candidate.  We can do a little testing here and there and then if all is well, we can tag 3.0 as done tomorrow?

**Pull request merged**
