### PR TITLE
Few more fixes

### PR DESCRIPTION
**Pull request by Myoldmopar**
A few more fixes coming in before we put it out there.  The main changes here are the cache file is now renamed without a version "3" suffix, and the bad workflows now fail gracefully.

@JasonGlazer On a side note, we do sorta need to settle on the version stuff.  Right now we have "3", but then we also have version 0.6 as the "version".  Maybe we can settle on this on Tuesday's call and get finalized and ready for release.

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I like the idea of going to 2.9.1 for Beta.  The only remaining issue I definitely know about is the choice field display on Mac.  I verified it's still happening, and that a quick fix I thought of one night did not address it.  It's going to take a little time to debug.  You have a Mac too right?  Or maybe I'm remembering wrong.  Anyway, if I could get someone to reproduce the issue that would be great.

**Comment by JasonGlazer** [comment]
Yes, I have a mac. I don't think I've started it in a year. I will give it a shot.

**Comment by Myoldmopar** [comment]
@JasonGlazer I added pubsub back into the requirements file, so future development setups will get it automatically.

**Comment by Myoldmopar** [comment]
@JasonGlazer There's one spot that still has "EPLaunch3" and could use a quick discussion.  It's here: https://github.com/NREL/EP-Launch/blob/619a0086c0febeed38f1462728dc112457c2d7eb/eplaunch/interface/frame.py#L42

This is simply the "key" used for saving/loading user config data.  I think it would be great to eliminate that 3, and just use the key "EPLaunch".  The only downside is that it will reset all your settings that you've acquired during development.  On the positive note, this would be a good test to make sure the frame works right on the "first" launch of it for a new user.  Let me know if you have a strong feeling either way.

**Comment by JasonGlazer** [comment]
Lets get rid of the wx.Config reference to "3"

**Comment by Myoldmopar** [comment]
Without the workaround on Mac, the choice is definitely attempting to render, because the spacing is correct, and I can `print` the size of the tool and it is appropriate.  However, it is blank.  It's definitely something that we are doing though, because I created a little dummy toolbar+choice box window and it runs beautifully.  As can be seen here:

image

**Comment by JasonGlazer** [comment]
weird. it is like it is hidden or something.

**Comment by Myoldmopar** [comment]
@JasonGlazer OK, I'm pushing up the version increment to 2.91.  Then I'm going to go ahead and merge this.  AFAIK the only thing I didn't get to is the Mac UI problem.  I want to merge this, and kick off a release, before too many people get it running and then have things reset due to the config/cache file changes in this PR.

**Pull request merged**
