### PR TITLE
Minor enhancements

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addressing minor enhancements for 3.1 release

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@Myoldmopar this addresses 

- #125 
- #117  
- #31  
- #90 

I think it is ready for review and merging.

**Comment by Myoldmopar** [comment]
How does this fit with the other PR?  Should they be merged in a certain order?

**Comment by JasonGlazer** [comment]
Hopefully there are no conflicts but I'm not certain. I would do the add_groups one first and then see if this one has conflicts. If so, I will fix.

**Comment by Myoldmopar** [comment]
No conflicts, but I'll probably still pull the main branch in just to make sure there aren't incidental side effects.

**Comment by Myoldmopar** [comment]
This is looking great.  The workflow version placement makes much more sense now.  The stale column looks to be working fine.  The external viewer setting is good to go.  I didn't test the explorer change on Windows yet, but it definitely didn't break the "Explorer" usage on Linux.  I'm happy to merge this one in.

**Comment by Myoldmopar** [comment]
Everything checks out, merging this one in.

**Pull request merged**
