### PR TITLE
Cache Files and Other Fixups

### PR DESCRIPTION
**Pull request by Myoldmopar**
This addresses a few things about cache files:

- [X] #20 Cache files now handle directory changes, woo!  The `self.current_cache` variable is still available for the current folder -- though I think I may remove it.  But now, when a workflow is done, we look up the appropriate directory for that workflow and write to that cache file.
- [X] #21 Now we don't update the current directory when a workflow is complete unless we are still in the same directory
- [X] #33 Moved FileNameMenus to single file structure
- [x] #22 Cache file needs to be blocked to avoid race conditions on the cache file write process

### CODE REVIEW

**Comment by Myoldmopar** [comment]
This is all of a sudden very nearly ready to go in.  I'm sure the coverage won't be 100% since I added in a bunch of debug prints that won't be exercised.  But I'll pragma them away.  Things are working really well.

**Comment by Myoldmopar** [comment]
You might notice that it looks like a ton of lines have changed on this PR.  There have been a good number of improvements, but some of it is also rearranging the frame.py code.  The code for handling different things was unorganized.  Now if you collapse the code in the IDE, you'll see it's organized.  I'd like to consider unifying some of the method names a little more too, but that can wait a little while.

image

**Comment by Myoldmopar** [comment]
OK I think I'm going to go ahead and merge this all in, please take a look at it and play with it.  I'd suggest setting up a few test folders without any cache files initially, and drop in some idfs and start running in multiple directories, then make sure the cache file matches the output files in each directory, etc.  It's a huge improvement!

**Comment by JasonGlazer** [comment]
@Myoldmopar lots of changes! I will take a look.

**Comment by JasonGlazer** [comment]
@Myoldmopar I'm getting a module not found error. Did you forget to commit a a file containing eplaunch.interface.frame_support?

**Comment by Myoldmopar** [comment]
How in **the** heck did Travis pass without that file?  Well I added it.  For some reason it was ignored by the .gitignore file, but I can't tell which pattern ignored it.  Anyway, it's in master, give it a pull and try again.  Thanks!

**Comment by JasonGlazer** [comment]
@Myoldmopar now it is reporting that it cannot import FileNameMenus

**Comment by Myoldmopar** [comment]
OK, so I found that the entire eplaunch/ folder was [added](https://github.com/NREL/EP-Launch/commit/0ef89327b9bcef95ba08b4a067be9057c51eeb39#diff-a084b794bc0759e7a6b77810e01874f2R111) to the .gitignore file.  So any new files added or tree changes weren't being added to the index.  Fixed that and now we're good to go I think!  Pull master again and let's see.

**Comment by JasonGlazer** [comment]
Thanks. It runs now. I will do some testing.

**Pull request merged**
